# 数据库Schema配置文件
# 支持静态配置和动态获取模式

# 配置模式: static(静态) | dynamic(动态) | hybrid(混合)
mode: "dynamic"

# 全局设置
settings:
  max_tables_per_database: 5     # 每个数据库最多处理的表数量
  max_fields_per_table: 8        # 每个表最多显示的字段数量
  max_sample_records: 3          # 每个表最多显示的样本记录数量
  enable_statistics: true        # 是否包含统计信息
  enable_enum_values: false      # 是否包含枚举值（数据量大，默认关闭）
  enable_sample_data: true       # 是否包含样本数据

# 数据库配置
databases:
  htinfo_db:
    name: "HT信息数据库"
    description: "包含沃尔玛产品、主题和订单等核心业务数据"
    enabled: true
    tables:
      walmart_online_item:
        name: "沃尔玛在线商品表"
        description: "沃尔玛在线商品信息，包括商品ID、名称、价格等"
        priority: 1
        
      walmart_online_theme:
        name: "沃尔玛在线主题表"
        description: "沃尔玛在线商品主题分类信息"
        priority: 2
        
      walmart_orders:
        name: "沃尔玛订单表"
        description: "沃尔玛订单信息，包括订单详情、时间、金额等"
        priority: 3

  ext_ref_db:
    name: "外部参考数据库"
    description: "包含亚马逊和沃尔玛的外部参考数据，用于市场分析和产品对比"
    enabled: true
    tables:
      amazon_products:
        name: "亚马逊产品表"
        description: "亚马逊产品信息，包括ASIN、标题、价格、分类等"
        priority: 1
        
      amazon_reviews:
        name: "亚马逊评价表"
        description: "亚马逊产品用户评价，包括评分、评价内容、时间等"
        priority: 2
        
      amazon_categories:
        name: "亚马逊分类表"
        description: "亚马逊产品分类信息"
        priority: 3
        
      walmart_products:
        name: "沃尔玛产品表"
        description: "沃尔玛产品详细信息，用于与亚马逊产品对比"
        priority: 4
        
      walmart_categories:
        name: "沃尔玛分类表"
        description: "沃尔玛产品分类信息"
        priority: 5
        
      walmart_product_images:
        name: "沃尔玛产品图片表"
        description: "沃尔玛产品图片链接信息"
        priority: 6

# 动态获取模式的配置
dynamic_config:
  # 当mode为dynamic或hybrid时，如果静态配置不存在或获取失败，使用动态获取
  fallback_to_dynamic: true
  # 动态获取时的数据库过滤规则
  database_filter:
    include: ["htinfo_db", "ext_ref_db"]
    exclude: ["information_schema", "mysql", "performance_schema", "log", "mindsdb", "files"]
  # 动态获取时的表过滤规则
  table_filter:
    exclude_patterns: ["tmp_*", "temp_*", "_backup", "log_*"]
    include_patterns: ["*"]

# 特定分析场景的提示
analysis_hints:
  amazon_reviews_analysis: |
    对于亚马逊产品评价分析，主要使用以下表：
    - ext_ref_db.amazon_reviews: 包含评分、评价内容、时间等
    - ext_ref_db.amazon_products: 包含产品信息，可与评价表关联
    - 关键字段：rating (评分), review_text (评价内容), review_date (评价时间), asin (产品标识)
    
  walmart_sales_analysis: |
    对于沃尔玛销售分析，主要使用以下表：
    - htinfo_db.walmart_orders: 包含订单信息
    - htinfo_db.walmart_online_item: 包含商品信息
    - ext_ref_db.walmart_products: 包含详细产品信息
    
  cross_platform_comparison: |
    对于跨平台产品对比分析：
    - 亚马逊数据：ext_ref_db.amazon_products, ext_ref_db.amazon_reviews
    - 沃尔玛数据：ext_ref_db.walmart_products, htinfo_db.walmart_orders

# 模板配置
templates:
  database_summary: |
    ## 数据库 {database_name}
    {description}
    
    **可用表:** {table_list}
    
  table_detail: |
    ### 表 {table_name}
    **描述:** {description}
    **数据库:** {database_name}
    
    **重要提示:** 
    - 亚马逊相关表 (amazon_*) 位于 ext_ref_db 数据库
    - 沃尔玛相关表分布在 htinfo_db 和 ext_ref_db 两个数据库
    - 查询时请确保使用正确的数据库名称

# 常见查询模式
common_patterns:
  rating_distribution: |
    -- 评分分布分析模板
    SELECT rating, COUNT(*) as count, 
           ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM ext_ref_db.amazon_reviews), 2) as percentage
    FROM ext_ref_db.amazon_reviews 
    WHERE rating BETWEEN 1 AND 5
    GROUP BY rating 
    ORDER BY rating;
    
  time_trend_analysis: |
    -- 时间趋势分析模板
    SELECT DATE_FORMAT(review_date, '%Y-%m') as month, COUNT(*) as review_count
    FROM ext_ref_db.amazon_reviews
    WHERE review_date >= '2023-01-01'
    GROUP BY DATE_FORMAT(review_date, '%Y-%m')
    ORDER BY month;
    
  product_category_analysis: |
    -- 产品分类分析模板
    SELECT p.category_id, AVG(r.rating) as avg_rating, COUNT(r.review_id) as review_count
    FROM ext_ref_db.amazon_products p 
    JOIN ext_ref_db.amazon_reviews r ON p.asin = r.asin
    GROUP BY p.category_id
    ORDER BY avg_rating DESC;